Repository airplanedev/views, pull requests merged in 2023-11, with the labels that each got.

#125 Include row in custom component props
  lib/src/@types/react-table-config.types.ts
  lib/src/components/table/Cell.tsx
  lib/src/components/table/Table.test.tsx
  lib/src/components/table/Table.types.ts
Labels: merge

#127 Release 2.1.15
  examples/adminPanel/package.json
  lib/package.json
Labels: release, merge

#128 Go to page 1 when page is empty after data change
  lib/src/components/table/Table.test.tsx
  lib/src/components/table/TableComponent.tsx
Labels: bug-fix, merge

#130 Release 2.1.16
  examples/adminPanel/package.json
  lib/package.json
Labels: release, merge

#132 Add runbooks and pages to view peeks
  examples/adminPanel/package.json
  lib/package.json
  lib/src/message/ViewMessage.ts
  lib/src/routing/useRouter.test.tsx
  lib/src/routing/useRouter.ts
Labels: merge

#133 Support task caching for views queries
  examples/adminPanel/src/App.tsx
  lib/package.json
  lib/src/client/env.ts
  lib/src/client/executeTask.ts
  lib/src/message/ViewMessage.ts
  lib/src/state/tasks/useTaskQuery.ts
  yarn.lock
Labels: merge
