Repository airplanedev/views, pull requests merged in 2023-04, with the labels that each got.

#17 Bump version to 2.0.5
  examples/adminPanel/package.json
  lib/package.json
Labels: release

#19 Remove contextual ligatures in views
  examples/adminPanel/index.html
  lib/src/components/theme/theme.ts
Labels: bug-fix, merge

#20 Change npm rc publish logic
  .github/workflows/tests.yaml
Labels: merge

#24 Pass peek params to web
  lib/src/message/ViewMessage.ts
  lib/src/routing/useRouter.test.tsx
  lib/src/routing/useRouter.ts
Labels: feature, merge

#26 Add stacked bar chart
  lib/src/components/chart/Chart.stories.tsx
  lib/src/components/chart/Chart.types.ts
  lib/src/components/chart/buildLayout.ts
Labels: merge

#27 Release v2.1.0-rc.1
  examples/adminPanel/package.json
  lib/package.json
Labels: merge

#33 Add ability to customize the chart axis ranges
  lib/src/components/chart/Chart.stories.tsx
  lib/src/components/chart/Chart.types.ts
  lib/src/components/chart/buildLayout.test.ts
  lib/src/components/chart/buildLayout.ts
Labels: feature, merge

#34 Improve chart loading state
  lib/src/components/chart/Chart.stories.tsx
  lib/src/components/chart/Chart.test.tsx
  lib/src/components/chart/ChartComponent.tsx
  lib/src/components/chart/ConnectedChart.tsx
Labels: merge

#32 Fix a few bugs on the request dialog
  lib/src/client/types.ts
  lib/src/components/avatar/Avatar.tsx
  lib/src/components/requestDialog/RequestRunnableDialog.test.tsx
  lib/src/components/requestDialog/RequestRunnableDialog.tsx
Labels: bug-fix, merge

#39 Bump views to 2.1.0-rc.2
  examples/adminPanel/package.json
  lib/package.json
Labels: release, merge

#41 Pass peek params to web (#24)
  lib/src/message/ViewMessage.ts
  lib/src/routing/useRouter.test.tsx
  lib/src/routing/useRouter.ts
Labels: merge

#42 Release 2.0.6
  lib/package.json
Labels: merge
