Repository airplanedev/views, pull requests merged in 2023-09, with the labels that each got.

#91 Serialize objects when downloading to CSV
  lib/src/components/table/Table.stories.tsx
  lib/src/components/table/csvUtils.ts
Labels: bug-fix, merge

#92 Allow formatting of Table cells when downloaded as CSV
  lib/src/@types/react-table-config.types.ts
  lib/src/components/table/Table.stories.tsx
  lib/src/components/table/TableComponent.tsx
  lib/src/components/table/csvUtils.test.ts
  lib/src/components/table/csvUtils.ts
Labels: feature, merge

#93 Release v2.1.8
  examples/adminPanel/package.json
  lib/package.json
Labels: release, merge

#85 Support self-hosted uploads from views
  lib/src/client/endpoints.ts
  lib/src/client/env.ts
  lib/src/components/fileinput/useUploadAirplaneFiles.tsx
  lib/src/env.d.ts
Labels: merge

#95 Release v2.1.9
  examples/adminPanel/package.json
  lib/package.json
Labels: release, merge

#96 Fix small typo
  lib/src/@types/react-table-config.types.ts
Labels: merge

#89 Implement hidden validate & regex task backed form
  lib/src/client/endpoints.ts
  lib/src/client/types.ts
  lib/src/components/form/Form.tsx
  lib/src/components/form/FormWithRunnable.test.tsx
  lib/src/components/form/jst.ts
  lib/src/components/form/parameters.tsx
  lib/src/state/components/input/runValidation.ts
Labels: merge

#104 Release v2.1.10
  examples/adminPanel/package.json
  lib/package.json
Labels: release, merge

#97 Update js-sdk version and set useSelfHostedInputs
  lib/jest-setup.ts
  lib/package.json
  lib/src/client/env.ts
  yarn.lock
Labels: merge

#100 Export marker that says when a task is executing
  lib/src/state/tasks/useTaskQuery.test.ts
  lib/src/state/tasks/useTaskQuery.ts
Labels: feature, merge

#103 Support task backed select in views task backed form
  lib/package.json
  lib/src/client/types.ts
  lib/src/components/form/Form.tsx
  lib/src/components/form/FormWithRunnable.test.tsx
  lib/src/components/form/parameters.tsx
  lib/src/components/select/Select.tsx
  lib/src/state/components/form/useFormState.ts
  lib/src/test-utils/tasks/executeTaskTestUtils.tsx
  yarn.lock
Labels: merge

#107 Release 2.1.11
  examples/adminPanel/package.json
  lib/package.json
Labels: release, merge

#109 Update js-sdk version in views
  lib/package.json
  yarn.lock
Labels: merge
