Repository airplanedev/views, pull requests merged in 2023-05, with the labels that each got.

#38 Use padding with tab panel instead of margin
  lib/src/components/tabs/Tabs.styles.ts
Labels: bug-fix, merge

#43 Delete outdated Table accessor comment
  lib/src/components/table/Table.types.ts
Labels: merge

#25 Upgrade to storybook 7 and node 18
  .github/workflows/chromatic.yml
  .nvmrc
  lib/.storybook/main.cjs
  lib/package.json
  lib/src/components/Typography.stories.tsx
  lib/src/components/avatar/Avatar.stories.tsx
  lib/src/components/button/Button.stories.tsx
  lib/src/components/callout/Callout.stories.tsx
  lib/src/components/card/Card.stories.tsx
  lib/src/components/chart/Chart.stories.tsx
  lib/src/components/checkbox/Checkbox.stories.tsx
  lib/src/components/chip/Chip.stories.tsx
  lib/src/components/code/Code.stories.tsx
  lib/src/components/codeinput/CodeInput.stories.tsx
  lib/src/components/datepicker/DatePicker.stories.tsx
  lib/src/components/datepicker/DateTimePicker.stories.tsx
  lib/src/components/descriptionList/DescriptionList.stories.tsx
  lib/src/components/dialog/Confirmation.stories.tsx
  lib/src/components/dialog/Dialog.stories.tsx
  lib/src/components/divider/Divider.stories.tsx
  lib/src/components/errorBoundary/AirplaneInternalErrorModal.stories.tsx
  lib/src/components/errorBoundary/ComponentErrorBoundary.stories.tsx
  lib/src/components/errorBoundary/ComponentErrorModal.stories.tsx
  lib/src/components/errorBoundary/ComponentErrorState.stories.tsx
  lib/src/components/errorBoundary/ErrorBoundary.stories.tsx
  lib/src/components/errorBoundary/ErrorFallback.stories.tsx
  lib/src/components/fileinput/FileInput.stories.tsx
  lib/src/components/form/Form.stories.tsx
  lib/src/components/heading/Heading.stories.tsx
  lib/src/components/icon/Icon.stories.tsx
  lib/src/components/image/Image.stories.tsx
  lib/src/components/layout/Layout.stories.tsx
  lib/src/components/link/Link.stories.tsx
  lib/src/components/loader/Loader.stories.tsx
  lib/src/components/markdown/Markdown.stories.tsx
  lib/src/components/multiselect/MultiSelect.stories.tsx
  lib/src/components/notification/Notification.stories.tsx
  lib/src/components/notification/RunnableErrorNotification.stories.tsx
  lib/src/components/number/NumberInput.stories.tsx
  lib/src/components/progressBar/ProgressBar.stories.tsx
  lib/src/components/radioGroup/RadioGroup.stories.tsx
  lib/src/components/requestDialog/RequestRunnableDialog.stories.tsx
  lib/src/components/samples/Dashboard.stories.tsx
  lib/src/components/samples/KitchenSink.stories.tsx
  lib/src/components/select/Select.stories.tsx
  lib/src/components/slider/Slider.stories.tsx
  lib/src/components/stack/Stack.stories.tsx
  lib/src/components/switch/Switch.stories.tsx
  lib/src/components/table/Table.stories.tsx
  lib/src/components/tabs/Tabs.stories.tsx
  lib/src/components/text/Label.stories.tsx
  lib/src/components/text/Text.stories.tsx
  lib/src/components/textarea/Textarea.stories.tsx
  lib/src/components/textinput/TextInput.stories.tsx
  lib/src/components/title/Title.stories.tsx
  lib/src/components/tooltip/Tooltip.stories.tsx
  yarn.lock
Labels: merge

#46 Reverse text preset and heading preset
  lib/src/@types/mantine-theme.d.ts
  lib/src/components/heading/Heading.tsx
  lib/src/components/table/Table.styles.ts
  lib/src/components/tabs/Tabs.styles.ts
  lib/src/components/text/Text.styles.ts
  lib/src/components/theme/theme.ts
  lib/src/components/theme/typography.ts
  lib/src/components/title/Title.tsx
Labels: merge

#52 Use Storybook light theme
  lib/.storybook/manager.js
  lib/package.json
  yarn.lock
Labels: merge

#51 Fix loading chart label bug
  lib/src/components/chart/ChartComponent.tsx
Labels: merge

#53 Grow chart to 100% of container
  lib/src/components/chart/Chart.stories.tsx
  lib/src/components/chart/ChartComponent.tsx
Labels: merge

#56 Explicitly set chart height
  examples/adminPanel/package.json
  lib/package.json
  lib/src/components/chart/Chart.stories.tsx
  lib/src/components/chart/ChartComponent.tsx
Labels: merge

#21 Do not execute on focus by default
  lib/src/state/tasks/useTaskQuery.ts
Labels: breaking-change, merge

#57 Release views 2.1.0
  examples/adminPanel/package.json
  lib/package.json
Labels: release, merge
